setup:
	@echo "Creating FOXX application file"
	rm -f guesser-foxx.zip
	cd ../.. && zip docker/arangodb/guesser-foxx.zip guesser.js manifest.json scripts/setup.js scripts/teardown.js README.md LICENSE
